# Generated by Django 6.0.6 on 2026-06-09 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Коллекция",
                "verbose_name_plural": "Коллекции",
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
            },
        ),
        migrations.CreateModel(
            name="Cage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                ("size", models.CharField(max_length=50, verbose_name="Размер")),
                ("material", models.CharField(max_length=255, verbose_name="Материал")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Image/%Y/%m/%d",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления на сайт"
                    ),
                ),
                (
                    "is_exists",
                    models.BooleanField(
                        default=True, verbose_name="Доступность к заказу"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bird_app.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "collection",
                    models.ManyToManyField(
                        to="bird_app.collection", verbose_name="Коллекция"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клетка",
                "verbose_name_plural": "Клетки",
            },
        ),
        migrations.CreateModel(
            name="Bird",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                ("age", models.PositiveIntegerField(verbose_name="Возраст (мес.)")),
                ("color", models.CharField(max_length=255, verbose_name="Окрас")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Image/%Y/%m/%d",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления на сайт"
                    ),
                ),
                (
                    "is_exists",
                    models.BooleanField(
                        default=True, verbose_name="Доступность к заказу"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bird_app.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "collection",
                    models.ManyToManyField(
                        to="bird_app.collection", verbose_name="Коллекция"
                    ),
                ),
            ],
            options={
                "verbose_name": "Птица",
                "verbose_name_plural": "Птицы",
            },
        ),
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                ("size", models.CharField(max_length=50, verbose_name="Размер")),
                ("color", models.CharField(max_length=255, verbose_name="Цвет")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Image/%Y/%m/%d",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления на сайт"
                    ),
                ),
                (
                    "is_exists",
                    models.BooleanField(
                        default=True, verbose_name="Доступность к заказу"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bird_app.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "collection",
                    models.ManyToManyField(
                        to="bird_app.collection", verbose_name="Коллекция"
                    ),
                ),
            ],
            options={
                "verbose_name": "Аксессуар",
                "verbose_name_plural": "Аксессуары",
            },
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                ("weight", models.FloatField(verbose_name="Вес (кг)")),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления на сайт"
                    ),
                ),
                (
                    "is_exists",
                    models.BooleanField(
                        default=True, verbose_name="Доступность к заказу"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bird_app.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bird_app.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корм",
                "verbose_name_plural": "Корма",
            },
        ),
    ]
