# Generated by Django 6.0.6 on 2026-06-09 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bird_app.supplier",
                verbose_name="Поставщик",
            ),
        ),
    ]
