# Generated by Django 6.0.6 on 2026-06-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_app", "0003_order_pos_order_order_accessory"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.FloatField(default=0, verbose_name="Сумма заказа"),
        ),
    ]
