# Generated by Django 6.0.6 on 2026-06-16 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_app", "0004_order_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="pos_order",
            name="bird",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bird_app.bird",
                verbose_name="Птица",
            ),
        ),
        migrations.AddField(
            model_name="pos_order",
            name="cage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bird_app.cage",
                verbose_name="Клетка",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="accessory",
            field=models.ManyToManyField(
                blank=True,
                through="bird_app.Pos_order",
                to="bird_app.accessory",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="pos_order",
            name="accessory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bird_app.accessory",
                verbose_name="Аксессуар",
            ),
        ),
    ]
